const { withGradleProperties } = require("@expo/config-plugins");

/**
 * Build for phones, not for emulators.
 *
 * React Native ships its native libraries four times over - once for each CPU
 * Android runs on - and a default release APK carries all four. Two of them,
 * x86 and x86_64, exist for emulators on a developer's laptop. No phone sold
 * in India has ever needed them, and in this app they were 46 MB of a 100 MB
 * download: nearly half the file, for a machine that is not a phone.
 *
 * Dropping them leaves armeabi-v7a and arm64-v8a, which between them cover
 * every real Android device, and takes the APK to about 54 MB.
 *
 * The cost is that the app no longer runs on an x86 emulator. It is not how
 * anything here is tested - the phone is - and `npx expo run:android` on an
 * emulator can still pass the architecture back on the command line:
 *
 *   ./gradlew assembleDebug -PreactNativeArchitectures=x86_64
 *
 * This is a config plugin rather than an edit to android/gradle.properties
 * because that whole folder is regenerated by prebuild and is not in git, so
 * anything written there by hand is lost the next time it runs.
 */

const PHONE_ARCHITECTURES = "armeabi-v7a,arm64-v8a";

const withPhoneArchitectures = (config) =>
    withGradleProperties(config, (cfg) => {
        const line = cfg.modResults.find(
            (item) => item.type === "property" && item.key === "reactNativeArchitectures",
        );

        if (line) {
            line.value = PHONE_ARCHITECTURES;
            return cfg;
        }

        cfg.modResults.push({
            type: "property",
            key: "reactNativeArchitectures",
            value: PHONE_ARCHITECTURES,
        });

        return cfg;
    });

module.exports = withPhoneArchitectures;
