const { withAppBuildGradle } = require("@expo/config-plugins");

/**
 * Sign release builds with the real key, not the debug one.
 *
 * Expo's generated app/build.gradle points the release build type at
 * `signingConfigs.debug` - the throwaway key that ships with every React
 * Native project. That is fine while EAS does the building, because EAS
 * replaces the signing itself; it is not fine here, where Gradle is the whole
 * build. An APK signed with the debug key is one the Play Store refuses and
 * one no phone will accept as an update of an existing install.
 *
 * The key is the same one EAS holds - downloaded from it - so a build made on
 * this machine and a build made in the cloud are interchangeable as far as
 * Play is concerned. That is the point of doing it this way rather than
 * generating a fresh keystore: a second key would fork the app in two.
 *
 * Credentials live in keystore.properties beside the project, which is in
 * .gitignore and in .easignore. Nothing secret is written into the repository
 * or shipped to a build server.
 *
 * A machine without those files still builds. The config falls back to the
 * debug key and says so, because a developer running a release build to check
 * that it compiles should not be stopped by a missing key - only a build meant
 * for a store needs the real one, and that build is made here.
 */

const SIGNING_CONFIG = `
        release {
            /*
             * Read at configure time from keystore.properties, which sits
             * beside the project rather than inside android/ - that folder is
             * regenerated by prebuild and anything left in it is lost.
             */
            def props = new Properties()
            def propsFile = rootProject.file('../keystore.properties')

            if (propsFile.exists()) {
                propsFile.withInputStream { props.load(it) }
                storeFile rootProject.file('../' + props.getProperty('storeFile'))
                storePassword props.getProperty('storePassword')
                keyAlias props.getProperty('keyAlias')
                keyPassword props.getProperty('keyPassword')
            } else {
                println 'keystore.properties not found - release will be signed with the debug key and cannot go to the Play Store'
                storeFile file('debug.keystore')
                storePassword 'android'
                keyAlias 'androiddebugkey'
                keyPassword 'android'
            }
        }
`;

const withReleaseSigning = (config) =>
    withAppBuildGradle(config, (cfg) => {
        let contents = cfg.modResults.contents;

        if (contents.includes("keystore.properties")) return cfg;

        /* ---- add a release signing config beside the debug one ---- */

        const debugConfig = `        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }`;

        if (!contents.includes(debugConfig)) {
            throw new Error(
                "withReleaseSigning could not find the debug signingConfig in app/build.gradle. "
                + "Expo changed the template; update plugins/withReleaseSigning.js."
            );
        }

        contents = contents.replace(debugConfig, debugConfig + "\n" + SIGNING_CONFIG);

        /* ---- and point the release build type at it ---- */

        const releaseUsesDebug = `            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig signingConfigs.debug`;

        if (!contents.includes(releaseUsesDebug)) {
            throw new Error(
                "withReleaseSigning could not find the release build type's debug signing. "
                + "Expo changed the template; update plugins/withReleaseSigning.js."
            );
        }

        contents = contents.replace(
            releaseUsesDebug,
            "            signingConfig signingConfigs.release"
        );

        cfg.modResults.contents = contents;
        return cfg;
    });

module.exports = withReleaseSigning;
